[personal]
    first_name = "Krystof"
    last_name = "Spiller"

    [personal.info]
        homepage = 'krystofs.com'
        linkedin = "krystof-spiller"
        github = "krystofspiller"
        email = "krystof.spiller@gmail.com"
        location = "Copenhagen"

[layout]
    accent_color = "#c25700"

    [layout.fonts]
        regular_font = "Source Sans 3"
        header_font = "Roboto"

[lang]
    header_quote = "Senior Software Engineer | Developing customer-centric solutions"
    resume_footer = "Resume"
    letter_footer = "Cover letter"